version: '3.8'

services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./config/sidekiq.rb
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
